name: flutter_webview_plugin_example
description: Demonstrates how to use the flutter_webview_plugin plugin.
version: 0.3.12
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.1

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin:
    path: ../

flutter:
  uses-material-design: true
